version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/elixir:1.7
        environment:
          MIX_ENV: test
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Revision }}
            - v1-build-cache
      - run: mix do deps.get, compile
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Revision }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"

      - run: mix test

      - run: mix format --check-formatted

      - store_test_results:
          path: _build/test/lib/docs
